name: Update Readme

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run update script
        run: | 
            sudo chmod 777 update_readme.sh
            ./update_readme.sh
            
      - uses: actions/upload-artifact@v3   
        with:
          name: Build    
          path: output/readme.txt

     
