name: Update Readme

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run update script
        run: | 
            sudo chmod 777 update_readme.sh
            ./update_readme.sh
        

      - name: Commit and push changes
        run: |
          git config user.email "gobikaponnusamy2003@gmail.com"
          git config user.name "gobikaponnusamy"
          git add output/readme.txt
          git commit -m "Update readme with PR info [skip ci]"
          git push
